### ISSUE TITLE
Run All -> Couldn't find test file 'rspec'!

### ISSUE THREAD

**Issue by quazimodo** [guard/guard-zeus#16]
rails (4.1.6)
guard (2.8.2)
guard-rspec (4.3.1)
guard-zeus (2.0.0)
zeus (0.15.3)
```
$ guard start
WARN: Unresolved specs during Gem::Specification.reset:
      listen (~> 2.7)
      formatador (>= 0.2.4)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
11:20:13 - INFO - Guard here! It looks like your project has a Gemfile, yet you are running
> [#] `guard` outside of Bundler. If this is your intent, feel free to ignore this
> [#] message. Otherwise, consider using `bundle exec guard` to ensure your
> [#] dependencies are loaded correctly.
> [#] (You can run `guard` with --no-bundler-warning to get rid of this message.)
11:20:13 - INFO - Guard::Zeus Initialized
11:20:13 - INFO - Guard is using Libnotify to send notifications.
11:20:13 - INFO - Guard is using Emacs to send notifications.
11:20:13 - INFO - Guard is using TerminalTitle to send notifications.
11:20:13 - INFO - Starting Zeus
11:20:13 - INFO - Guard is now watching at '/home/quazimodo/Webapps/flickr-example'
Starting Zeus server v0.15.3
[ready] [crashed] [running] [connecting] [waiting]
boot
└── default_bundle
    ├── development_environment
    │   └── prerake
    └── test_environment
        └── test_helper

Available Commands: [waiting] [crashed] [ready]
zeus rake
zeus runner (alias: r)
zeus console (alias: c)
zeus server (alias: s)
zeus generate (alias: g)
zeus destroy (alias: d)
zeus dbconsole
[1] guard(main)>  rspec, testrb)
11:20:37 - INFO - Run all
Couldn't find test file 'rspec'!
```

The issue is that ```Guard::Zeus::Runner#run_all``` will ```run(['rspec'])``` which causes ```Guard::Zeus::Runner#run_command``` to send ```zeus test rspec``` to system, which  really ought to be ```zeus test spec```

Am I wrong here?

**Comment by saiqulhaq** [comment]
I get this issue also
this my `guard --debug` result

    22:34:24 - DEBUG - Hook :run_all_begin executed for Guard::Zeus
    Couldn't find test file 'rspec'!
    22:34:26 - DEBUG - Hook :run_all_end executed for Guard::Zeus

**Comment by qnm** [comment]
@quazimodo Any chance you could create a repo for me with a failing example?

**Comment by e2** [comment]
I had the same issue - confirmed it, confirmed the fix and it should work on master.

Worth releasing as 2.0.1, because it's such a confusing error.

Ideally, the spec dir would be "detected" - but there's really no clean way to do that I guess. Everyone uses 'spec' everywhere anyway.

**Comment by qnm** [comment]
@e2 Thanks mate. I'll update the version and push.

**Comment by quazimodo** [comment]
@qnm sorry buddy i was swamped for a bit there. Just came to make that repo but looks like you've got it sorted :)
