### ISSUE TITLE
Exiting guard leaves lingering zeus processes

### ISSUE THREAD

**Issue by suan** [guard/guard-zeus#26]
I'm on OSX Yosemite. From what I can tell exiting guard does not actually exit zeus - i.e. the `zeus-darwin-amd64 start` process is still there long after guard has exited. Is this to be expected?

**Comment by qnm** [comment]
Hey @suan, thanks for the issue.

Can you elaborate on how you're exiting guard? Are you using ctrl-c or typing exit?

 -- Rob

**Comment by e2** [comment]
Running `guard -d` may give hints as to if the `:stop` method is properly called. 

Guard should at least say "Bye bye...".

**Comment by suan** [comment]
@qnm I'm typing `exit` in the guard prompt. I do see the "Bye bye" and some message along the lines of "Stopping Zeus..." but the Zeus process itself persists. Don't see anything else that's unexpected.

**Comment by suan** [comment]
Any update on this?

**Comment by qnm** [comment]
@suan I'm building a test repo to reproduce the case. I'll let you know how I get on.

**Comment by qnm** [comment]
@suan Could you please paste the full log displayed, from running `guard` to the guard process exiting?Thanks.

**Comment by qnm** [comment]
@suan I can't reliably repeat the behaviour you've seen.

I've added some debugging to the latest alpha - `2.0.1.pre.alpha.pre.92`.

Can update to `2.0.1.pre.alpha.pre.92` and repeat your test with `guard -d` so I can see debugging.

Please paste the log in here.

**Comment by tgaff** [comment]
I think I'm seeing this too.

```
bash-3.2$ ps -ef | grep zeus
  501 87783 87765   0  1:52PM ttys003    0:00.00 grep zeus
bash-3.2$ bundle exec guard
13:52:16 - INFO - Guard::Zeus Initialized
13:52:16 - INFO - Starting Zeus
13:52:16 - INFO - Guard is now watching at '/Users/tgaff/devel/OfficeHours'
[1] guard(main)> Starting Zeus server v0.15.4
[ready] [crashed] [running] [connecting] [waiting]
boot
└── default_bundle
    ├── development_environment
    │   └── prerake
    └── test_environment
        └── test_helper

Available Commands: [waiting] [crashed] [ready]
zeus rake
zeus runner (alias: r)
zeus console (alias: c)
zeus server (alias: s)
zeus generate (alias: g)
zeus destroy (alias: d)
zeus dbconsole
zeus test (alias: rspec, testrb)
[1] guard(main)> exit
13:52:23 - INFO - Guard::Zeus is deleting an unusable .zeus.sock
13:52:23 - INFO - Zeus Stopped

13:52:23 - INFO - Bye bye...
bash-3.2$ ps -ef | grep zeus
  501 87800     1   0  1:52PM ttys003    0:00.08 /Users/tgaff/.gem/ruby/2.1.3/gems/zeus-0.15.4/build/fsevents-wrapper
  501 87801     1   0  1:52PM ttys003    0:00.90 zeus slave: boot
  501 87802 87801   0  1:52PM ttys003    0:00.44 zeus slave: default_bundle
  501 87803 87802   0  1:52PM ttys003    0:00.73 zeus slave: development_environment   GREP_COLOR=1;33
  501 87804 87802   0  1:52PM ttys003    0:00.79 zeus slave: test_environment
  501 87805 87803   0  1:52PM ttys003    0:00.01 zeus slave: prerake
  501 87806 87804   0  1:52PM ttys003    0:00.32 zeus slave: test_helper
  501 87817 87765   0  1:52PM ttys003    0:00.00 grep zeus

bash-3.2$ grep guard Gemfi
Gemfile       Gemfile.lock
bash-3.2$ grep guard Gemfile.lock
    guard (2.13.0)
    guard-compat (1.2.1)
    guard-rspec (4.6.4)
      guard (~> 2.1)
      guard-compat (~> 1.1)
    guard-zeus (2.0.1)
      guard (~> 2.0)
      guard-compat (~> 1.1)
  guard
  guard-rspec
  guard-zeus
```

**Comment by tgaff** [comment]
I updated to 
```
GIT
  remote: git@github.com:guard/guard-zeus.git
  revision: 6b712f8b3b2c6949a78ce7d3b2e9891b7912edaf
```
And while I found that it doesn't leave zeus running, it also doesn't allow me to continue using that terminal.  The terminal accepts input but doesn't display it on screen.

**Comment by tgaff** [comment]
`bundle exec guard -d ` output:
```
14:10:12 - INFO - Guard::Zeus Initialized
14:10:12 - DEBUG - Notiffany: gntp not available (Please add "gem 'ruby_gntp'" to your Gemfile and run your app with "bundle exec".).
14:10:12 - DEBUG - Notiffany: growl not available (Please add "gem 'growl'" to your Gemfile and run your app with "bundle exec".).
14:10:12 - DEBUG - Notiffany: terminal_notifier not available (Please add "gem 'terminal-notifier-guard'" to your Gemfile and run your app with "bundle exec".).
14:10:12 - DEBUG - Notiffany: libnotify not available (Unsupported platform "darwin14.3.0").
14:10:12 - DEBUG - Notiffany: notifysend not available (Unsupported platform "darwin14.3.0").
14:10:12 - DEBUG - Notiffany: notifu not available (Unsupported platform "darwin14.3.0").
14:10:12 - DEBUG - Command execution: {"ALTERNATE_EDITOR"=>"false"} emacsclient --eval '1'
14:10:12 - DEBUG - Notiffany: emacs not available (Emacs client failed).
14:10:12 - DEBUG - Notiffany: tmux not available (:tmux notifier is only available inside a TMux session.).
14:10:12 - DEBUG - Notiffany: file not available (No :path option given).
14:10:12 - DEBUG - Notiffany is using TerminalTitle to send notifications.
14:10:12 - DEBUG - Command execution: hash stty
14:10:12 - DEBUG - Guard starts all plugins
14:10:12 - DEBUG - Hook :start_begin executed for Guard::Zeus
14:10:12 - DEBUG - Stopping Zeus
14:10:12 - INFO - Starting Zeus
14:10:12 - DEBUG - About to spawn zeus
14:10:12 - DEBUG - Zeus has PID 94586
14:10:12 - DEBUG - Hook :start_end executed for Guard::Zeus
14:10:12 - INFO - Guard is now watching at '/Users/travis/devel/OfficeHours'
14:10:12 - DEBUG - Start interactor
14:10:12 - DEBUG - Command execution: stty -g 2>/dev/null
[1] guard(main)> Starting Zeus server v0.15.4
[ready] [crashed] [running] [connecting] [waiting]
boot
└── default_bundle
    ├── development_environment
    │   └── prerake
    └── test_environment
        └── test_helper

Available Commands: [waiting] [crashed] [ready]
zeus rake
zeus runner (alias: r)
zeus console (alias: c)
zeus server (alias: s)
zeus generate (alias: g)
zeus destroy (alias: d)
zeus dbconsole
zeus test (alias: rspec, testrb)
[1] guard(main)> exit
14:10:18 - DEBUG - Interactor was stopped or killed
14:10:18 - DEBUG - Command execution: stty  2>/dev/null
14:10:18 - DEBUG - Guard stops all plugins
14:10:18 - DEBUG - Hook :stop_begin executed for Guard::Zeus
14:10:18 - DEBUG - Stopping Zeus
14:10:18 - DEBUG - Stopping Zeus using a PID
14:10:18 - DEBUG - Killing process 94586
14:10:18 - DEBUG - Killed process 94586
14:10:18 - DEBUG - Set process 94586 to wait
14:10:18 - DEBUG - Killing process 94586 after wait
14:10:18 - INFO - Killed process 94586 after wait
14:10:18 - INFO - Zeus Stopped
14:10:18 - DEBUG - Hook :stop_end executed for Guard::Zeus

14:10:18 - INFO - Bye bye...
```

**Comment by e2** [comment]
If it helps, Guard has an "non-interactive" mode (`-i` parameter), where you exit with Ctrl-C. The Zeus process should get killed either way.

**Comment by suan** [comment]
Sorry for not responding earlier, but with the latest versions of Guard (2.13.0) and zeus (0.15.4) zeus processes are correctly terminated... _except when they're actively being used_ (e.g. there's a Rails console that was started using zeus open in another window)

In that situation, the zeus process(es) still stick around after guard exits, and unfortunately don't go away after the console is closed. It appears however that at this point the `master` process is gone as you get the `Can't connect to master` message when trying to issue a zeus command.

When guard is started up again it goes and starts a whole new zeus session, leaving that old one there forever until it's manually killed.

I'm not sure what's the best way to improve this, but having all these lingering zeus processes significantly slows everything down for large apps. In the meantime I've coped by putting a `at_exit { system("pkill -f 'zeus'") }` in my `Guardfile`

**Comment by qnm** [comment]
@suan I may present that as an option e.g. `:kill_zeus_on_exit => true`. It seems to be a common-enough case. Honestly, I'm not sure how to work around any other way.

Any thoughts on exposing that command as an option, @e2?

**Comment by e2** [comment]
@qnm - `at_exit` is definitely overkill, as the `stop()` method should handle things here:

https://github.com/guard/guard-zeus/blob/master/lib/guard/zeus/runner.rb#L109

Killing all 'zeus' procs seems like overkill too (especially if you have multiple projects).

There might be a proper way to kill the right processes by using `Process.getsid`:

http://ruby-doc.org/core-2.2.3/Process.html#method-c-getsid

(and killing everything with the same session id).

As a shortcut, a command may be: ```system('kill', `ps -s #{pid} -o pid=`)``` ... and then killing the main process last.

Ultimately, I think this process iteration and killing should be handled by zeus (if possible).

As for Guard, killing inside `stop()` should be sufficient.

**Comment by e2** [comment]
I think there's an alternative using the idea that the process's parent ID becomes 1 (or 0) when the parent dies. 

I don't know if zeus sets a group ID.

(Sorry I won't have time to play around to check).

**Comment by smit1625** [comment]
I agree with @e2 about killing all zeus processes being overkill for those of us who like to run multiple projects at the same time now and then.  It seems to me that, while many other guards claim to integrate with this gem, a lot of them aren't handling exits properly because the main zeus process exits before they do.

I also noticed that (at least on my OS X 10.11.1 machine) zeus is leaving `fsevents-wrapper` processes running after exit, which seem to stack up one at a time.

I'm thinking about making a fork that would compare the output of something like `ps aux | grep "zeus slave\|fsevents-wrapper"` before and after zeus is booted (so that we only are concerning ourselves with the current instance of zeus), and then write the pids of all those processes to some file in tmp and kill them at the end of `stop`.

It would also be great if someone more knowledgable than I could contribute some insight as to how zeus might be forced to start first and stop last when guard is started, stopped, or reloaded.

**Comment by e2** [comment]
@smit1625 

> I also noticed that (at least on my OS X 10.11.1 machine) zeus is leaving fsevents-wrapper processes running after exit, which seem to stack up one at a time.

This may be a different bug - probably best to report it on the zeus project itself. I used to have a similar issue with inotify-wrapper (I use Linux, not OSX) - and I patched back then. Ideally the wrapper should close by itself, see: https://github.com/burke/zeus/blob/c9640df0adca36212902805b41c1fc31d9618543/ext/fsevents/main.m#L82

(reading input should fail if the stream is close, and the wrapper should exit the loop when that happens).

> It seems to me that, while many other guards claim to integrate with this gem, a lot of them aren't handling exits properly because the main zeus process exits before they do.

Best to handle this case-by-case. You can report it and then just mention me (@e2). I need to be at least able to reproduce the problem (a separate repo reproducing the problem would help get this fixed faster).

> It would also be great if someone more knowledgable than I could contribute some insight as to how zeus might be forced to start first and stop last when guard is started, stopped, or reloaded.

Best to analyze this case-by-case. Guard supports "callbacks" (see docs), but I don't think that's a clean solution.

**Comment by xecutioner** [comment]
I've figured out a temporary way to make this work by using at_exit hook .
`at_exit {exec('pkill -f zeus')}`

**Comment by qnm** [comment]
> I've figured out a temporary way to make this work by using at_exit hook .
> at_exit {exec('pkill -f zeus')}

The problem with that approach is that a user may have multiple `zeus` processes across many apps, and this will kill all of them. Hence, we can't make that a default.

I've added it to the [README](https://github.com/guard/guard-zeus#lingering-zeus-process).
